---
- title: DNS Abuse SIG
  url: /global/sigs/dns
  nav:
    - title: DNS Abuse Techniques Matrix
      url: /global/sigs/dns/DNS-Abuse-Techniques-Matrix_v1.1.pdf
    - title: Stakeholder Advice
      url: /global/sigs/dns/stakeholder-advice/
      nav:    
        - title: Detection
          nav:
            - title: Cache Poisoning
                url: /global/sigs/dns/stakeholder-advice/detection/cache-poisoning
            - title: Creation of Malicious Subdomains Under Dynamic DNS Providers
                url: /global/sigs/dns/stakeholder-advice/detection/creation-of-malicious-subdomains-under-dynamic-dns-providers
            - title: DGA Domains
                url: /global/sigs/dns/stakeholder-advice/detection/dga
            - title: DNS As a Vector for DoS
                url: /global/sigs/dns/stakeholder-advice/detection/dns-as-a-vector-for-dos
            - title: DNS Beacons - C2 Communication
                url: /global/sigs/dns/stakeholder-advice/detection/dns-beacons-c2-communication
            - title: DNS Rebinding
                url: /global/sigs/dns/stakeholder-advice/detection/dns-rebinding
            - title: DNS Server Compromise
                url: /global/sigs/dns/stakeholder-advice/detection/dns-server-compromise
            - title: DNS Tunneling
                url: /global/sigs/dns/stakeholder-advice/detection/dns-tunneling
            - title: DoS Against the DNS
                url: /global/sigs/dns/stakeholder-advice/detection/dos-against-the-dns
            - title: Domain Name Compromise
                url: /global/sigs/dns/stakeholder-advice/detection/domain-name-compromise
            - title: Dynamic DNS (as obfuscation technique)
                url: /global/sigs/dns/stakeholder-advice/detection/dynamic-dns-resolution-as-obfuscation-technique
            - title: Fast Flux (as obfuscation technique)
                url: /global/sigs/dns/stakeholder-advice/detection/fast-flux
            - title: Infiltration and exfiltration via the DNS
                url: /global/sigs/dns/stakeholder-advice/detection/infiltration-and-exfiltration-via-the-dns
            - title: Lame Delegations
                url: /global/sigs/dns/stakeholder-advice/detection/lame-delegations
            - title: Local Resolver Hijacking
                url: /global/sigs/dns/stakeholder-advice/detection/local-resolver-hijacking
            - title: Malicious registration of (effective) second level domains
                url: /global/sigs/dns/stakeholder-advice/detection/malicious-registration-of-effective-second-level-domains
            - title: On-path DNS Attack
                url: /global/sigs/dns/stakeholder-advice/detection/on-path-dns-attack
            - title: Stub Resolver Hijacking
                url: /global/sigs/dns/stakeholder-advice/detection/stub-resolver-hijacking
            - title: Spoofing of a Registered Domain
                url: /global/sigs/dns/stakeholder-advice/detection/spoofing-of-a-registered-domain
            - title: Spoofing of Unregistered Domains
                url: /global/sigs/dns/stakeholder-advice/detection/spoofing-of-unregistered-domains
    - title: Code of Conduct & Other Policies
      url: /global/sigs/dns/policies
    - title: Examples of DNS Abuse
      url: /global/sigs/dns/dns-abuse-examples
